### ISSUE TITLE
广告误杀和漏捡多吗

### ISSUE THREAD

**Issue by PowerDi** [zqzess/rule_for_quantumultX#1]
如题

**Comment by zqzess** [comment]
我自己用的时候没发现误杀，感觉去广告主要体现在爱奇艺视频去广告，网页搜索上

**Comment by PowerDi** [comment]
主要还是开屏广告太恶心了！ 耗电量有感吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqzess <notifications@github.com&gt;
发送时间: 2020年11月18日 13:43
收件人: zqzess/rule_for_quantumultX <rule_for_quantumultX@noreply.github.com&gt;
抄送: PowerDi <578661971@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zqzess/rule_for_quantumultX] 广告误杀和漏捡多吗 (#1)





 
我自己用的时候没发现误杀，感觉去广告主要体现在爱奇艺视频去广告，网页搜索上

**Comment by zqzess** [comment]
耗电量正常，开屏广告几乎都去不了，之前路由器端架了个adguard home也就是让开屏广告加载不出来，但是该等5秒还是要等，这玩意好像得配合脚本才能去，单分流规则不起作用，github上有大佬做了b站去开屏广告脚本，我用了没啥作用，提示已经wifi预加载，去缓存还是这样，放弃了

**Comment by zqzess** [comment]
个人觉得去广告最完美的还是路由器上用adguard home，看盗版小说app30秒全屏广告能给你降到1秒，quanX去广告只是为了看视频查资料舒服点

**Comment by PowerDi** [comment]
可是在外面怎么办呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqzess <notifications@github.com&gt;
发送时间: 2020年11月18日 14:35
收件人: zqzess/rule_for_quantumultX <rule_for_quantumultX@noreply.github.com&gt;
抄送: PowerDi <578661971@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zqzess/rule_for_quantumultX] 广告误杀和漏捡多吗 (#1)

**Comment by PowerDi** [comment]
耗电量虽然有统计问题 但是我能明显感觉到电量不耐用 也不知道为什么



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqzess <notifications@github.com&gt;
发送时间: 2020年11月18日 14:31
收件人: zqzess/rule_for_quantumultX <rule_for_quantumultX@noreply.github.com&gt;
抄送: PowerDi <578661971@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zqzess/rule_for_quantumultX] 广告误杀和漏捡多吗 (#1)





 
耗电量正常，开屏广告几乎都去不了，之前路由器端架了个adguard home也就是让开屏广告加载不出来，但是该等5秒还是要等，这玩意好像得配合脚本才能去，单分流规则不起作用，github上有大佬做了b站去开屏广告脚本，我用了没啥作用，提示已经wifi预加载，去缓存还是这样，放弃了

**Comment by zqzess** [comment]
在外面就靠quanX啊，去广告差了点，但是还是有作用的。耗电量只要不开调试，我感觉还是很正常，比shadowrocket和pharos耗电低很多

**Comment by zqzess** [comment]
如果对某个app开屏广告很厌烦，可以去找找这个app的去广告重写和脚本，单分流规则不行的

**Comment by PowerDi** [comment]
看来我来对比下亮屏情况 开关quanx下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zqzess <notifications@github.com&gt;
发送时间: 2020年11月18日 14:40
收件人: zqzess/rule_for_quantumultX <rule_for_quantumultX@noreply.github.com&gt;
抄送: PowerDi <578661971@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[zqzess/rule_for_quantumultX] 广告误杀和漏捡多吗 (#1)





 
在外面就靠quanX啊，去广告差了点，但是还是有作用的。耗电量只要不开调试，我感觉还是很正常，比shadowrocket和pharos耗电低很多
