### ISSUE TITLE
youtube广告可以跳过，但是每次跳过广告，视频都会重头开始播放

### ISSUE THREAD

**Issue by zhufeizzz** [zqzess/rule_for_quantumultX#10]
美国节点，每次都是这样，好难受。

**Comment by zqzess** [comment]
试了下，没遇到这个问题，我身边人也没遇到，给个链接我看看

**Comment by zhufeizzz** [comment]
> 试了下，没遇到这个问题，我身边人也没遇到，给个链接我看看

iphone12 ios15 油管16.44.5均为最新版
每个视频都不行，我试了下网页版没问题

**Comment by zqzess** [comment]
确实有这个问题，但貌似不是所有视频都会这样。暂时没找到原因，试了下神机规则的也有这个问题

**Comment by DarrickBM** [comment]
iphone 12 pro
ios 14.8 
youtube 16.45.4 
现在每个视频都会碰到这个问题，特别难受T-T
