### ISSUE TITLE
每当跳过一个广告时就会重新播放

### ISSUE THREAD

**Issue by lowkeyrookie** [zqzess/rule_for_quantumultX#11]
第一个广告不会出现问题，当跳过第二个时就会重新播放，应该是最近YouTube更新后出现的，现在用的这个重写不会出问题https://raw.githubusercontent.com/jimmyorz/Surge/master/YouTube.sgmodule

**Comment by zqzess** [comment]
都是这样，我昨天琢磨了好久，发现github上现有规则都有这个问题。目前只能尝试回退版本或者开会员
