### ISSUE TITLE
就要个去开屏广告的，是不是引入 重写规则 就可以了？

### ISSUE THREAD

**Issue by mtgq** [zqzess/rule_for_quantumultX#12]

**Comment by zqzess** [comment]
MyAdBlock.qxrewrite就可以了，但是圈X的重写不支持规则分流，有一部分广告屏蔽的分流规则单独写在ReFix.list里面，loon或者surge找对应的就好了

**Comment by mtgq** [comment]
好的，谢谢大佬，我就一个圈x😀

**Comment by mtgq** [comment]
> MyAdBlock.qxrewrite就可以了，但是圈X的重写不支持规则分流，有一部分广告屏蔽的分流规则单独写在ReFix.list里面，loon或者surge找对应的就好了

大佬有没有tg啊？

**Comment by zqzess** [comment]
> > MyAdBlock.qxrewrite就可以了，但是圈X的重写不支持规则分流，有一部分广告屏蔽的分流规则单独写在ReFix.list里面，loon或者surge找对应的就好了
> 
> 大佬有没有tg啊？

@zqzess
