### ISSUE TITLE
谷歌搜索用不了了

### ISSUE THREAD

**Issue by ZFC5932** [zqzess/rule_for_quantumultX#15]
我用日本和香港的节点能打开，用韩国节点就404
![1E40B9C5-8B0F-4E65-B039-7FDD4CDEA406](https://user-images.githubusercontent.com/21293739/153203598-07b401f1-cddb-4acc-a57c-93d460303a50.png)

**Comment by zqzess** [comment]
你节点问题呀，有点节点在墙查的严的时候会多次重定向然后出错，换节点好了，这个不能改，改了别人可能会出错

**Comment by yak007** [comment]
其中这一段改成这样，就不会404了
`[rewrite_local]
^https:\/\/www.google.cn\/* url 302 https://www.google.com/
^https:\/\/www.google.co.jp\/* url 302 https://www.google.com/
^https:\/\/www.google.com.hk\/* url 302 https://www.google.com/ `

**Comment by zqzess** [comment]
不是，你节点问题啊，这个很早就有大佬讲过原因的，换个节点，这种问题通常发生在国内每年开会期间，每年这个时候都会有人来反馈说这个问题，不管怎么改总归有人会404，但是大部分人都是正常的

**Comment by zqzess** [comment]
> 其中这一段改成这样，就不会404了
> 
> > [rewrite_local]
> > ^https://www.google.cn/* url 302 https://www.google.com/
> > ^https://www.google.co.jp/* url 302 https://www.google.com/
> > ^https://www.google.com.hk/* url 302 https://www.google.com/


不是，你节点问题啊，这个很早就有大佬讲过原因的，换个节点，这种问题通常发生在国内每年开会期间，每年这个时候都会有人来反馈说这个问题，不管怎么改总归有人会404，但是大部分人都是正常的

**Comment by TributePaulWalker** [comment]
> 我用日本和香港的节点能打开，用韩国节点就404
> ![1E40B9C5-8B0F-4E65-B039-7FDD4CDEA406](https://user-images.githubusercontent.com/21293739/153203598-07b401f1-cddb-4acc-a57c-93d460303a50.png)

你节点问题而已
