### ISSUE TITLE
百度贴吧开屏选择兴趣，点了之后，退后台重新进又要选择，个人资料主页面也是崩溃

### ISSUE THREAD

**Issue by fengfeichanxue** [zqzess/rule_for_quantumultX#17]
![image](https://user-images.githubusercontent.com/97719768/179383205-85bd267f-ecf2-42fd-971a-51fed9e64308.png)

**Comment by zqzess** [comment]
把圈x关了，然后打开并登入贴吧，之后再开启圈x

**Comment by fengfeichanxue** [comment]
好啦，感谢大佬，感谢> 把圈x关了，然后打开并登入贴吧，之后再开启圈x

**Comment by fengfeichanxue** [comment]
大佬还有一个问题，引用资源重写里面，搬运脚本合集出问题了> 把圈x关了，然后打开并登入贴吧，之后再开启圈x

**Comment by zqzess** [comment]
``MyJsRewrite.conf``这个文件嘛，这个是要开启资源解析器的

**Comment by fengfeichanxue** [comment]
> ``MyJsRewrite.conf``这个文件嘛，这个是要开启资源解析器的
解析器我开了的
![image](https://user-images.githubusercontent.com/97719768/179383720-d535051c-f2e7-4089-a625-c615cc56f7ae.png)

**Comment by zqzess** [comment]
哦哦这个我也发现了，是Peng-YM大佬的一个油猴脚本转换器删除了，我没把这个移除

**Comment by fengfeichanxue** [comment]
> 哦哦这个我也发现了，是Peng-YM大佬的一个油猴脚本转换器删除了，我没把这个移除

我要怎么弄好呢

**Comment by zqzess** [comment]
现在再更新一下就没了，如果更新还存在，可能是缓存，就等5分钟再更新

**Comment by fengfeichanxue** [comment]
> 现在再更新一下就没了，如果更新还存在，可能是缓存，就等5分钟再更新

好的，感谢
