### ISSUE TITLE
番茄小说去广告失效

### ISSUE THREAD

**Issue by gclm** [zqzess/rule_for_quantumultX#19]
报错日志如下

Left side MitM error for i-lq.snssdk.com with optional ssl code -9808.

**Comment by zqzess** [comment]
应该还没失效，5.2.7使用正常。你这个报错应该是你其它规则冲突了，这个域名在我的规则里是不走mitm的，直接reject

**Comment by gclm** [comment]
1. 我用的就是你提供的规则，番茄版本为5.4.5
2. 规则坐标： https://github.com/zqzess/rule_for_quantumultX/blob/master/QuantumultX/zqzess_lite.conf

**Comment by zqzess** [comment]
淦，这个里面的番茄小说规则忘记更新了，很久之前的版本的，因为后来把番茄小说的独立出去的，我等下更新一下，你晚点手动更新一下就好了

**Comment by gclm** [comment]
OK，感谢

**Comment by zqzess** [comment]
我已经推送更新了，你现在更新试试看，把ReFix分流规则和重写规则更新一下

**Comment by gclm** [comment]
我已经更新了。现在可以正常使用了。

**Comment by gclm** [comment]
又不行，感觉不稳啊。广告偶尔还有

**Comment by zouhy2001** [comment]
确实 今天间歇有广告了

**Comment by zqzess** [comment]
你们都用的最新版的吗，我没用最新版，等我用了试试看

**Comment by zqzess** [comment]
5.2.7版本可以正常屏蔽广告的，后面的版本因为我没更新过，不清楚，稍微等一段时间，这玩意不是一直能刷出广告来

**Comment by zouhy2001** [comment]
> 你们都用的最新版的吗，我没用最新版，等我用了试试看

用的v 5.4.5 应该是最新版

**Comment by zqzess** [comment]
> > 你们都用的最新版的吗，我没用最新版，等我用了试试看
> 
> 用的v 5.4.5 应该是最新版

那就是最新版，我已经更新了，暂时还没刷出广告

**Comment by zouhy2001** [comment]
> > > 你们都用的最新版的吗，我没用最新版，等我用了试试看
> > 
> > 
> > 用的v 5.4.5 应该是最新版
> 
> 那就是最新版，我已经更新了，暂时还没刷出广告

![1181259A-1F8F-418C-8B56-0D0947F90436](https://user-images.githubusercontent.com/57806936/187012116-110e3fd2-d212-4fb2-9c1e-7f668c8d3055.png)

还有一个misc.fqnovel 没具体分析

**Comment by zqzess** [comment]
用了一下，没有广告出现，正常的，只是章末会出现玩游戏赚番茄逛商城这种按钮。我找人问了，也是正常屏蔽，偶尔有广告也不影响，开qx看几章就没了。可能是有广告缓存。建议清缓存试试，或者删除app重装。

**Comment by zqzess** [comment]
不过我还是更新了部分ReFix规则，暂时不清楚有什么影响，不知道会不会对字节系的其它app造成影响

**Comment by zouhy2001** [comment]
前几天beta系统用不了quanx 当时关了看了一下子 那估计是当时缓存了发自我的 iPhone在 2022年8月28日，20:51，zqzess ***@***.***> 写道：﻿
用了一下，没有广告出现，正常的，只是章末会出现玩游戏赚番茄逛商城这种按钮。我找人问了，也是正常屏蔽，偶尔有广告也不影响，开qx看几章就没了。可能是有广告缓存。建议清缓存试试，或者删除app重装。

**Comment by MyLiuzibin** [comment]
失效了

**Comment by zqzess** [comment]
> 失效了

番茄小说版本版本5.4.7，没有失效，正常屏蔽。

如有广告加载，请尝试以下操作
- 检查圈x或surge或Loon启用状态是否正确，如surge关闭兼容模式，圈X激活状态
- 圈X需要重写和分流规则配合使用才能起效
- 保持代理工具开启，清理番茄小说缓存
- 如有开屏开屏广告说明使用番茄小说时未开启代理工具，广告已缓存过段时间会自动消失
- 保持代理工具开启，彻底删除并重装番茄小说
