### ISSUE TITLE
百度开屏广告好像失效了？

### ISSUE THREAD

**Issue by w12928293** [zqzess/rule_for_quantumultX#2]
用了好多去广告的分流和重写，但是还是有好多顽固广告没法根除。
用了楼主的去百度开屏广告的那段，测试了下，有时候打开有广告，有时候又没有，缓存也清理过，也重新安装过APP，好像还是这样，请教下是最近规则有变么？

**Comment by zqzess** [comment]
我抓了包发现广告规则没变，我自己使用也没有开屏广告。不过我改了一下正则表达式，不起作用你可以换新规则，
可能需要重装app才起效，
hostname可以使用dss0.bdstatic.com或*.bdstatic.com
下面的图片是使用的旧规则
![20210419182242](https://user-images.githubusercontent.com/54464797/115221922-be6f3180-a13c-11eb-9a32-9a70f7bcade4.jpg)
重装后记录能看到被**旧规则**屏蔽

**Comment by zqzess** [comment]
有时候不起作用可能是别的原因，前两天哔哩哔哩和知乎规则就是失效过

**Comment by w12928293** [comment]
感谢解答。
前几天出差忘了测试，这两天我把hostname改成*.bdstatic.com，正则没改，好像确实没广告了，感谢感谢！
