### ISSUE TITLE
番茄去广告失效了

### ISSUE THREAD

**Issue by zouhy2001** [zqzess/rule_for_quantumultX#21]
![042A2249-FD06-4617-A997-03EEC0A5C0AE](https://user-images.githubusercontent.com/57806936/192094287-5ba75fc8-c5e2-4942-8507-1c124f35f9b8.png)

**Comment by zqzess** [comment]
番茄小说版本V5.5.0，ios版本15.6.1，广告屏蔽正常。

我这边正常屏蔽，抓不了包啊

建议尝试以下操作：

- 检查圈x或surge或Loon启用状态是否正确，如surge关闭兼容模式，圈X激活状态
- 圈X需要重写和分流规则配合使用才能起效
- 保持代理工具开启，清理番茄小说缓存
- 如有开屏开屏广告说明使用番茄小说时未开启代理工具，广告已缓存过段时间会自动消失
- 保持代理工具开启，彻底删除并重装番茄小说
- 部分章末有小说推荐是正常的

**Comment by zouhy2001** [comment]
> 番茄小说版本V5.5.0，ios版本15.6.1，广告屏蔽正常。
> 
> 我这边正常屏蔽，抓不了包啊
> 
> 建议尝试以下操作：
> 
> * 检查圈x或surge或Loon启用状态是否正确，如surge关闭兼容模式，圈X激活状态
> * 圈X需要重写和分流规则配合使用才能起效
> * 保持代理工具开启，清理番茄小说缓存
> * 如有开屏开屏广告说明使用番茄小说时未开启代理工具，广告已缓存过段时间会自动消失
> * 保持代理工具开启，彻底删除并重装番茄小说
> * 部分章末有小说推荐是正常的

我是ios16 quanx从来没关过 反正我这看的网络记录,是有新域名能通过的,有新的字节的域名,而且广告有直接走广告商域名的,比如pdd.

**Comment by zqzess** [comment]
有可能是ios16问题，前几天也有几个人反馈又广告，也是ios16，我这边用的番茄小说最新版，但是是ios15。

ios16的话得过几个月，暂时不想升级

**Comment by zouhy2001** [comment]
> 有可能是ios16问题，前几天也有几个人反馈有广告，也是ios16，我这边用的番茄小说最新版，但是是ios15。
> 
> ios16的话得过几个月，暂时不想升级

番茄去广告脚本添加以下几条:

^https?:\/\/.+\.(pglstatp-toutiao|pstatp)\.com\/(ad-app-package|ad)\/.+ url reject
^https?:\/\/adim\.pinduoduo\.com\/. url reject
^https?:\/\/v6-novelapp\.fqnovelvod\.com\/. url reject

hostname=adim.pinduoduo.com,v6-novelapp.fqnovelvod.com

url reject依据 章末广告:
![image](https://user-images.githubusercontent.com/57806936/194868910-d1ddb279-1b62-4f34-984a-14b8c6342c99.png)

app开屏视频:
http://v6-novelapp.fqnovelvod.com/19c09a1b3581b771fee1eca6264d16f6/634550a4/video/tos/cn/tos-cn-ve-51-alinc2/ee287bd8f4074e00a4974479aa40eb69/?a=1967&ch=0&cr=3&dr=0&er=1&lr=default&cd=0%7C0%7C0%7C3&cv=1&br=734&bt=734&cs=0&ds=1&ft=W53zMNN6VlCwJIMZq8dzJLeOYZlc9yz.d2bL4ouf5DZm&mime_type=video_mp4&qs=0&rc=OmQ3ZThpaDU6OGg3OjdnM0BpanQ8aWY6Zm5nOzMzNDYzM0BgYTMtLzRfXy8xMS0tYS0vYSNnLjI1cjRfYS1gLS1kMC9zcw%3D%3D&l=2022101019160401020914616620F8B32D

**Comment by zqzess** [comment]
番茄小说广告屏蔽修复了。找到原因了，规则没问题，是一个分流规则被其他规则覆盖成直连了。以前没问题，感觉可能是圈x某次更新优先级改了。过会推送更新就可以用了。把番茄小说的分流单独分开了，以后会同时在ReFix.list和FanQieNovel.list里面更新，不想用ReFix的可以的单独订阅FanQieNovel.list。

**Comment by zouhy2001** [comment]
> 番茄小说广告屏蔽修复了。找到原因了，规则没问题，是一个分流规则被其他规则覆盖成直连了。以前没问题，感觉可能是圈x某次更新优先级改了。过会推送更新就可以用了。把番茄小说的分流单独分开了，以后会同时在ReFix.list和FanQieNovel.list里面更新，不想用ReFix的可以的单独订阅FanQieNovel.list。

我试试,有问题我再反馈
