### ISSUE TITLE
圈x解锁spotify

### ISSUE THREAD

**Issue by j1903059993** [zqzess/rule_for_quantumultX#25]
请问圈x是否可以解锁spotify会员

**Comment by zqzess** [comment]
> 请问圈x是否可以解锁spotify会员

重写：https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.conf

部分解锁premium 需iOS15 ,建议重新登录,音质不能设置为超高

[作者仓库](https://github.com/app2smile/rules)

**Comment by j1903059993** [comment]
谢谢回复---- 回复的原邮件 ***@***.***>发送日期2022年10月26日 11:46 ***@***.***> ***@***.******@***.***>主题Re: [zqzess/rule_for_quantumultX] 圈x解锁spotify (Issue #25)



请问圈x是否可以解锁spotify会员



重写：https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.conf

部分解锁premium 需iOS15 ,建议重新登录,音质不能设置为超高

作者仓库



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/zqzess/rule_for_quantumultX/issues/25#issuecomment-1291457383",

"url": "https://github.com/zqzess/rule_for_quantumultX/issues/25#issuecomment-1291457383",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
