### ISSUE TITLE
番茄小说是什么版本

### ISSUE THREAD

**Issue by inpunyint** [zqzess/rule_for_quantumultX#26]
试了清缓存和重装都没用

**Comment by zqzess** [comment]
番茄小说版本V5.5.3。
你是ios16吗。

**Comment by Space-Loon** [comment]
> 番茄小说版本V5.5.3。 你是ios16吗。

大佬，我番茄小说广告是没加载出来，但是广告的框还在，请问怎么处理?
手机系统：ios16.2
番茄小说版本 v5.5.3

**Comment by zqzess** [comment]
> > 番茄小说版本V5.5.3。 你是ios16吗。
> 
> 大佬，我番茄小说广告是没加载出来，但是广告的框还在，请问怎么处理? 重写和分流均已订阅 手机系统：ios16.2 番茄小说版本 v5.5.3

目前好像ios16的系统都会有广告，我没升级ios16，暂时不知道啥情况

**Comment by Space-Loon** [comment]
> > > 番茄小说版本V5.5.3。 你是ios16吗。
> > 
> > 
> > 大佬，我番茄小说广告是没加载出来，但是广告的框还在，请问怎么处理? 重写和分流均已订阅 手机系统：ios16.2 番茄小说版本 v5.5.3
> 
> 目前好像ios16的系统都会有广告，我没升级ios16，暂时不知道啥情况

好吧

**Comment by Space-Loon** [comment]
> > > 番茄小说版本V5.5.3。 你是ios16吗。
> 
> > 
> 
> > 大佬，我番茄小说广告是没加载出来，但是广告的框还在，请问怎么处理? 重写和分流均已订阅 手机系统：ios16.2 番茄小说版本 v5.5.3
> 
> 
> 
> 目前好像ios16的系统都会有广告，我没升级ios16，暂时不知道啥情况

大佬，我回来报告了
我同时在IOS16系统下的圈X和Loon两个代理软件内导入了你的规则重写，插件。
Loon可以完美屏蔽广告，圈X则会弹出广告的框架，但是不显示广告
所以我认为是圈X在16系统内，重写部分的适配没有做好

**Comment by htmlstart** [comment]
苹果系统：IOS 15.7.1 
番茄小说版本：V5.5.3
小火箭模块完美去广告
quantumultX大部分时候会出现黑色的广告框，偶尔会出现强制五秒的章末广告

**Comment by htmlstart** [comment]
已找到解决方案：
quantumultX关闭分流优化后，可以实现完美去除番茄小说广告

**Comment by zqzess** [comment]
> 已找到解决方案：
> quantumultX关闭分流优化后，可以实现完美去除番茄小说广告

你说的分流优化是ReFix分流规则吗？还有小火箭模块是什么，是小火箭新出的功能吗？

**Comment by htmlstart** [comment]
> > 已找到解决方案：
> > quantumultX关闭分流优化后，可以实现完美去 除番薯小说广告
> 
> 你说的分流优化是ReFix分流规则吗？还有小火箭模块是什么，是小火箭新出的功能吗？

是的，在默认情况下，Quantumult X 会启用「分流匹配优化」，大致的优先级先后顺序为：
HOST > HOST-SUFFIX > HOST-WILDCARD > HOST-KEYWORD > USER-AGENT > IP类型规则 (IP-CIDR 等)，所以番茄小说的分流规则放在哪里都不会生效，关闭分流优化就好了。

小火箭模块就是那个点击【配置】->【模块】的那个模块，跟圈X不一样，它是分流+重写弄在一起的

**Comment by zqzess** [comment]
> 

小火箭好久不用了，ReFix主要是分流一下没有被匹配的域名，由于圈x没有surge和loon那种模块，所以只能吧番茄小说的分流放refix里面。我已经弃坑圈x转surge了😂

**Comment by zqzess** [comment]
好了，修复了。找到原因了，规则没问题，是一个分流规则被其他规则覆盖成直连了。以前没问题，感觉可能是圈x某次更新优先级改了。过会推送更新就可以用了。把番茄小说的分流单独分开了，以后会同时在ReFix.list和FanQieNovel.list里面更新，不想用ReFix的可以的单独订阅FanQieNovel.list。
