### ISSUE TITLE
阿里云盘签到无效

### ISSUE THREAD

**Issue by JiuBoy** [zqzess/rule_for_quantumultX#28]
显示签到成功，但是到app上看还是可以签到，应该是没成功，但是签到返回又显示签到成功

**Comment by zqzess** [comment]
你可能看错了。我刚看了我账号是连签的，没有断过，你可以后天打开看看明天的有没有签到成功，或者开小号试试。
（开小号打开阿里云盘等待获取token，不要进去签到页面，然后手动执行脚本，等待签到成功通知，然后明天等他签到好了你再看看是不是签到成功2天）

签到成功是读取他返回值里的一个标签，这个标签只有每天第一次签到且成功才返回，读取不到这个标签是不会返回成功的

**Comment by zqzess** [comment]
> 显示签到成功，但是到app上看还是可以签到，应该是没成功，但是签到返回又显示签到成功

或者就是，你加了脚本获取token后没杀掉阿里云盘然后执行脚本签到了？这种情况下它会显示可以签到，因为它没刷新数据
