### ISSUE TITLE
抖音提示网络不给力

### ISSUE THREAD

**Issue by w12928293** [zqzess/rule_for_quantumultX#3]
今天打开抖音提示网络不给力。

看了下日志，发现是amemv.com这个域名没匹配到规则，手动添加了一条分流之后正常了，不过过一会又不行了。

![微信图片_20210610090016](https://user-images.githubusercontent.com/10286351/121448566-8234b080-c9ca-11eb-8d31-442deee6f32f.jpg)
![微信图片_20210610090011](https://user-images.githubusercontent.com/10286351/121448576-84970a80-c9ca-11eb-9a7b-c2c5b62c4165.jpg)

**Comment by zqzess** [comment]
这个应该是mitm无法解析，估计是抖音去广告脚本配置的hostname导致的，前两天有人发消息说抖音可能配置了加密

**Comment by zqzess** [comment]
> 今天打开抖音提示网络不给力。
> 
> 
> 
> 看了下日志，发现是amemv.com这个域名没匹配到规则，手动添加了一条分流之后正常了，不过过一会又不行了。
> 
> 
> 
> 
> 
> ![微信图片_20210610090016](https://user-images.githubusercontent.com/10286351/121448566-8234b080-c9ca-11eb-8d31-442deee6f32f.jpg)
> 
> ![微信图片_20210610090011](https://user-images.githubusercontent.com/10286351/121448576-84970a80-c9ca-11eb-9a7b-c2c5b62c4165.jpg)
> 
> 
> 
> 

我把圈x的抖音广告屏蔽移出了，如果你引用的我直接更新就好，或者mitm模块新增
-*.amemv.com

**Comment by w12928293** [comment]
神奇，我确实是引用的你的重写，不过更新完没效果，手动添加mitm后正常了，感谢！

这个是不是意味着抖音去广告和下载去水印无效了

**Comment by zqzess** [comment]
> 神奇，我确实是引用的你的重写，不过更新完没效果，手动添加mitm后正常了，感谢！
> 
> 
> 
> 这个是不是意味着抖音去广告和下载去水印无效了

更新完没效果，好像是一段时间内更新太频繁，以后去广告水印应该都没法用了

**Comment by w12928293** [comment]
看有没有转机吧，关注你的更新，先把这个issue关了

**Comment by w12928293** [comment]
应该是最近抖音的更新原因，我试着装回16.2.0版，去广告及去水印下载都正常。

**Comment by zqzess** [comment]
> 应该是最近抖音的更新原因，我试着装回16.2.0版，去广告及去水印下载都正常。

是的，最新版抖音都有防解密，不更新没这问题
