### ISSUE TITLE
阿里云盘签到无法自动获取cookie

### ISSUE THREAD

**Issue by luoxia-wen** [zqzess/rule_for_quantumultX#30]
在boxjs里进行了订阅，loon中添加了脚本，多次进入阿里云后没有任何提示，boxjs中也无法看到fresh_token

**Comment by zqzess** [comment]
你看一下token获取打开没有，你安装插件后，token获取默认关闭的，只有定时任务是开着的

**Comment by luoxia-wen** [comment]
> 你看一下token获取打开没有，你安装插件后，token获取默认关闭的，只有定时任务是开着的

**Comment by luoxia-wen** [comment]
你好，谢谢你的回复，token获取确实是灰色的，网盘签到是亮的，但是我不知道在loon中如何打开它

**Comment by zqzess** [comment]
你再安装一下这个[插件](https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/js/Mine/aDriveCheckIn/aDriveCheckIn_token.plugin)

我的问题，我记错了，我记得以前好像loon点进插件可以选择禁用启用某个脚本的

**Comment by zqzess** [comment]
获取到token后，记得把token获取插件关了，以后应该是用不到了，除非你阿里网盘退出登录可能需要刷新一遍token

**Comment by luoxia-wen** [comment]
好的，谢谢，提示获取token了，但是boxjs里好像fresh_token依然是空白的，这个有影响吗

**Comment by zqzess** [comment]
不影响，这个是给你拿到其他地方比如第三方阿里云盘app或者alist里面用的

你把boxjs杀掉重启再看看，应该就有了。如果是网页的话刷新一下试试

**Comment by luoxia-wen** [comment]
好的，谢谢
