### ISSUE TITLE
番茄小说最新版去广告失效

### ISSUE THREAD

**Issue by zhouxx2018** [zqzess/rule_for_quantumultX#31]
![82145C69-6AB2-420B-82AF-021FA5EA4FC1](https://user-images.githubusercontent.com/45591919/226169218-67e023d1-ef1a-4c6b-beeb-3627e0ff37c3.png)

手机系统是16.3.1，app版本是5.6.7，听说最新版禁用了mitm，不知道是不是这个原因，请问是否可以通过降app版本解决呢？

**Comment by zqzess** [comment]
不是mitm原因，也没有失效，你是圈x吧，应该是你最近规则更新了，有冲突

**Comment by zqzess** [comment]
看一下我仓库首页，已经标注了

**Comment by zhouxx2018** [comment]
> 不是mitm原因，也没有失效，你是圈x吧，应该是你最近规则更新了，有冲突

我把番茄的重写和分流放到了最上面，也不行，请问要怎么解决呢，一条条手动修改规则吗

**Comment by zqzess** [comment]
你可能需要把其他分流和重写全部禁用，然后依次开启一条试验是哪条冲突了

**Comment by zhouxx2018** [comment]
> 你可能需要把其他分流和重写全部禁用，然后依次开启一条试验是哪条冲突了

好的感谢
