### ISSUE TITLE
Duolingo/多邻国，不用Outside 的吧？

### ISSUE THREAD

**Issue by tanloo** [zqzess/rule_for_quantumultX#32]
多邻国国内应该可以直连，如果配置Outside走代理，会卡顿，有时候甚至加载不出来

**Comment by zqzess** [comment]
你可以把下面几天优先本地走直连。duolinguo国内确实可以直连，不过貌似国际版功能更多，查了一下貌似以前被墙过
<img width="258" alt="image" src="https://user-images.githubusercontent.com/54464797/226306024-95097d4e-64fd-4157-b5b0-6321f98764b1.png">
