### ISSUE TITLE
今日黄历

### ISSUE THREAD

**Issue by MissLeely** [zqzess/rule_for_quantumultX#36]
我最新版本qx使用今日黄历 一直无法运行 更没有推送   求救🆘

**Comment by zqzess** [comment]
QX-1.3.0-781

我这没啥问题啊

你看看你日志呢，你这啥也不说我也不知道咋回事

![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/c0df4629-7d39-423a-b2cf-006d80b50269)

**Comment by MissLeely** [comment]
> QX-1.3.0-781
> 
> 我这没啥问题啊
> 
> 你看看你日志呢，你这啥也不说我也不知道咋回事
> 
> ![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/c0df4629-7d39-423a-b2cf-006d80b50269)

![image](https://github.com/zqzess/rule_for_quantumultX/assets/59527278/9e72fbfc-76b5-4e65-bdce-ef1da804f9ea)


感觉已经启动了  不知道哪里限制了 继续运行

**Comment by zqzess** [comment]
这个是他代码改错了，没有加$done()让脚本结束运行，你先加我仓库里的脚本吧

**Comment by MissLeely** [comment]
> 这个是他代码改错了，没有加$done()让脚本结束运行，你先加我仓库里的脚本吧

使用了https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/js/Mine/wnCalendar/wnCalendar.js

![image](https://github.com/zqzess/rule_for_quantumultX/assets/59527278/032d5840-03ad-4524-8820-c4f4f1623b7d)

依然是这样的  脚本是别人给我的 他也是可以正常使用的  现在不知道是分流 还是广告屏蔽什么的限制了   现在是一头雾水   谢谢你的帮助  我再看看去

**Comment by zqzess** [comment]
不知道，这个好像是软件的问题，第一次遇见

**Comment by MissLeely** [comment]
我把版本降到1.20可以正常使用了   👌  谢谢解答

**Comment by zqzess** [comment]
我的是1.3，不过我是ios15，不知道是不是还和系统有关

**Comment by MissLeely** [comment]
> 我的是1.3，不过我是ios15，不知道是不是还和系统有关

我是15.3   

我不对  我好像是一开始没有推送才更新的圈x
不管了   现在有推送就安心了   折腾了好久
也谢谢你的解答
