### ISSUE TITLE
Qsearch 百度安全验证

### ISSUE THREAD

**Issue by jaylbj37** [zqzess/rule_for_quantumultX#38]
loon，Qsearch和百度搜索去广告插件一起用的时候，百度每次都是会跳出安全验证。
qx，没有此0问题。
折腾了半天没解决。请问是我配置问题，还是两插件冲突。
谢谢。

**Comment by zqzess** [comment]
不知道，百度搜索去广告是哪个。qx没问题可能是你配置出错了

**Comment by jaylbj37** [comment]
百度搜索去广告用的https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Loon/Plugin/BaiduSearchWebpage_remove_ads.plugin
在新建页面搜索，百度会跳出安全验证。在原有已打开页面搜索就不会跳出。
