### ISSUE TITLE
QX的配置需要更新一下

### ISSUE THREAD

**Issue by coderstory** [zqzess/rule_for_quantumultX#39]
geo_location_checker=http://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr?, https://raw.githubusercontent.com/ConnersHua/Quantumult/master/geo_location_checker.js

这个js的路径需要改一下 多了一个目录
https://raw.githubusercontent.com/ConnersHua/Quantumult/master/Script/geo_location_checker.js

**Comment by zqzess** [comment]
谢谢反馈，已更新
