### ISSUE TITLE
YouTube shorts不能播放，但是评论可以加载

### ISSUE THREAD

**Issue by w12928293** [zqzess/rule_for_quantumultX#4]
我试着将域名手动添加，或是新建分流也不行，可以显示画面，但是不能播放，评论可以正常加载。
![4](https://user-images.githubusercontent.com/10286351/122173431-4c089c80-ceb4-11eb-879a-917a7c749e2b.jpg)
![3](https://user-images.githubusercontent.com/10286351/122173436-4d39c980-ceb4-11eb-9e52-cf84df9a7aed.jpg)
![2](https://user-images.githubusercontent.com/10286351/122173438-4dd26000-ceb4-11eb-9620-a6ea4aa09755.jpg)
![1](https://user-images.githubusercontent.com/10286351/122173440-4e6af680-ceb4-11eb-9c9d-2d93e9d0a765.jpg)

**Comment by zqzess** [comment]
> 我试着将域名手动添加，或是新建分流也不行，可以显示画面，但是不能播放，评论可以正常加载。
> ![4](https://user-images.githubusercontent.com/10286351/122173431-4c089c80-ceb4-11eb-879a-917a7c749e2b.jpg)
> ![3](https://user-images.githubusercontent.com/10286351/122173436-4d39c980-ceb4-11eb-9e52-cf84df9a7aed.jpg)
> ![2](https://user-images.githubusercontent.com/10286351/122173438-4dd26000-ceb4-11eb-9620-a6ea4aa09755.jpg)
> ![1](https://user-images.githubusercontent.com/10286351/122173440-4e6af680-ceb4-11eb-9c9d-2d93e9d0a765.jpg)

有视频链接嘛，我试试看，我没遇到过这个问题

**Comment by w12928293** [comment]
ios端YouTube，中间位置 shorts beta版面
![5](https://user-images.githubusercontent.com/10286351/122174194-187a4200-ceb5-11eb-993d-9ca0cf7ba6b6.jpg)

**Comment by w12928293** [comment]
测试了一下，好像是#YouTuBe去广告的重写引起的，大佬有时间能不能更新下自用重新那部分？

**Comment by zqzess** [comment]
> 测试了一下，好像是#YouTuBe去广告的重写引起的，大佬有时间能不能更新下自用重新那部分？

我试了，规则冲突了，其他人的规则也有一样的问题，限制我更新了Qx的规则只保留了一个跳广告的规则，短视频有的能看有的不能看，不过正常的视频有的广告可能不能完全屏蔽。

**Comment by w12928293** [comment]
> > 测试了一下，好像是#YouTuBe去广告的重写引起的，大佬有时间能不能更新下自用重新那部分？
> 
> 我试了，规则冲突了，其他人的规则也有一样的问题，限制我更新了Qx的规则只保留了一个跳广告的规则，短视频有的能看有的不能看，不过正常的视频有的广告可能不能完全屏蔽。

好嘞，可能这个shorts正式上线之后会好点，只能先这样了，感谢调试！

**Comment by zqzess** [comment]
> > > 测试了一下，好像是#YouTuBe去广告的重写引起的，大佬有时间能不能更新下自用重新那部分？
> > 
> > 
> > 我试了，规则冲突了，其他人的规则也有一样的问题，限制我更新了Qx的规则只保留了一个跳广告的规则，短视频有的能看有的不能看，不过正常的视频有的广告可能不能完全屏蔽。
> 
> 好嘞，可能这个shorts正式上线之后会好点，只能先这样了，感谢调试！

我修改了正则，短视频现在可以正常看了。
我把YouTube规则单独分离了，下面是订阅地址
```
https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/rewrite/youtube.qxrewrite
```
由于不是每次都能遇到片头广告，所以麻烦注意一下，如果发现有片头广告没有成功跳过，记录并告知我*.googlevideo.com开头的请求记录
示例如图：
<table>
    <tr>
        <td ><center><img src="https://cdn.jsdelivr.net/gh/zqzess/pichouse/pic/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210616180121.jpg" width="250" height="500"/></center></td>
        <td ><center><img src="https://cdn.jsdelivr.net/gh/zqzess/pichouse/pic/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20210616180126.jpg" width="250" height="500"/></center></td>
    </tr>
</table>
