### ISSUE TITLE
阿里云盘获取cookie接口已改变

### ISSUE THREAD

**Issue by doyoman** [zqzess/rule_for_quantumultX#45]
阿里云盘获取cookie接口已改变，希望更新

**Comment by zqzess** [comment]
感谢反馈，阿里网盘换域名了，马上更新

**Comment by zqzess** [comment]
已更新，请更新脚本后重试

**Comment by aLIEz-xue** [comment]
大佬，loon使用插件获取不到cookie是怎么回事呢

**Comment by zqzess** [comment]
> 大佬，loon使用插件获取不到cookie是怎么回事呢

![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/18f949af-8130-4924-adca-9cf541af3b3a)

能获取，检查你的配置

**Comment by aLIEz-xue** [comment]
> > 大佬，loon使用插件获取不到cookie是怎么回事呢
> 
> ![image](https://user-images.githubusercontent.com/54464797/275698823-18f949af-8130-4924-adca-9cf541af3b3a.png)
> 
> 能获取，检查你的配置

好的，我再研究研究

**Comment by aLIEz-xue** [comment]
> > 大佬，loon使用插件获取不到cookie是怎么回事呢
> 
> ![image](https://user-images.githubusercontent.com/54464797/275698823-18f949af-8130-4924-adca-9cf541af3b3a.png)
> 
> 能获取，检查你的配置

研究了半天，还是获取不到，看到抓到请求了，但是没读到token，大佬方便指导下吗，谢谢

![loon-alipan-1](https://github.com/zqzess/rule_for_quantumultX/assets/59567929/19f7cf09-7eed-4280-a31a-8a8826e15f75)
![loon-alipan-2](https://github.com/zqzess/rule_for_quantumultX/assets/59567929/d44b71ca-ba69-4867-8b4d-f46e925597c1)
![loon-alipan-3](https://github.com/zqzess/rule_for_quantumultX/assets/59567929/ef6c9374-3166-49d3-80cb-59af08afe9a0)
![loon-alipan-4](https://github.com/zqzess/rule_for_quantumultX/assets/59567929/0007148b-687b-4fef-8c8d-b105125bbd8b)
