### ISSUE TITLE
番茄去广告激活的同时抖音收不到联系人和群聊的消息了，好像 115网盘的链接也会被拦截

### ISSUE THREAD

**Issue by SlowSSD** [zqzess/rule_for_quantumultX#48]

**Comment by zqzess** [comment]
抖音确实有这个问题，但是好像之前修过，我现在就是开番茄屏蔽，抖音聊天正常使用，你可以关了番茄屏蔽，用抖音聊天，再打开番茄屏蔽试试。

115链接，虽然我没用过115，但是应该不太可能，因为屏蔽的主要都是字节跳动的广告，115的链接域名应该都不在识别列表里，估计是你其他广告屏蔽规则导致的

**Comment by SlowSSD** [comment]
> 抖音确实有这个问题，但是好像之前修过，我现在就是开番茄屏蔽，抖音聊天正常使用，你可以关了番茄屏蔽，用抖音聊天，再打开番茄屏蔽试试。
> 
> 115链接，虽然我没用过115，但是应该不太可能，因为屏蔽的主要都是字节跳动的广告，115的链接域名应该都不在识别列表里，估计是你其他广告屏蔽规则导致的

是的，我发现了，115是我这的问题，抱歉，然后抖音还是不行，我直接新建规则让抖音走直连了

**Comment by zqzess** [comment]
我目前是没这个问题，也可能是规则冲突？今天有位老兄反馈说番茄规则失效了，整半天最后发现他添加了其他广告屏蔽规则导致失效

**Comment by SlowSSD** [comment]
> 我目前是没这个问题，也可能是规则冲突？今天有位老兄反馈说番茄规则失效了，整半天最后发现他添加了其他广告屏蔽规则导致失效

应该不是规则冲突的问题，我是由于之前添加的规则资源链接太多，一直启动失败，所以重装了圈x，目前我加入的规则跟重写只有番茄去广告，他命中了这两个链接，这两个应该是跟抖音直播有关，当然还有个群聊的连接他也会拦截，但我给他手动分流了![![image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/5a3958d1-c0e9-484d-80d3-8960df9e656c)image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/a3c56566-96af-4b4a-8cca-0ac9297f7090)

**Comment by SlowSSD** [comment]
> > 我目前是没这个问题，也可能是规则冲突？今天有位老兄反馈说番茄规则失效了，整半天最后发现他添加了其他广告屏蔽规则导致失效
> 
> 应该不是规则冲突的问题，我是由于之前添加的规则资源链接太多，一直启动失败，所以重装了圈x，目前我加入的规则跟重写只有番茄去广告，他命中了这两个链接，这两个应该是跟抖音直播有关，当然还有个群聊的连接他也会拦截，但我给他手动分流了![![image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/5a3958d1-c0e9-484d-80d3-8960df9e656c)image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/a3c56566-96af-4b4a-8cca-0ac9297f7090)

![image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/d29dd4fc-e2ba-4fb4-ac6c-e34087f8a01a)

**Comment by zqzess** [comment]
douyingcdn.com这个域名没做处理啊，规则里也没有。群聊的连接域名是哪个？

**Comment by zqzess** [comment]
你上图给的zijieapi.com的这个是群聊的吗？

**Comment by SlowSSD** [comment]
> douyincdn.com这个域名没做处理啊，规则里也没有。群聊的连接域名是哪个？
cdn这个是重写拦截的，群聊的连接域名是下面的这个
![image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/7d62b35c-f463-4642-ab81-5848f8ccd4ca)![image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/e7e983ea-4672-4dc2-b398-417d8d81a55f)

**Comment by zqzess** [comment]
奇了怪了，qx版本的番茄和surge的没同步吗

**Comment by SlowSSD** [comment]
> 你上图给的zijieapi.com的这个是群聊的吗？

是的，imapi3-normal-lf.zijieapi.com

**Comment by SlowSSD** [comment]
> 奇了怪了，qx版本的番茄和surge的没同步吗

![image](https://github.com/zqzess/rule_for_quantumultX/assets/62760761/72895b4f-dd63-4293-a60f-a46f7f53b2f5)刚刚又手动更新了一下，重写的那个链接跟分流的依然是这样，不过还是很好用，非常感谢你

**Comment by zqzess** [comment]
我看了，没同步。。。下次可以开解析器订阅surge的模块

**Comment by SlowSSD** [comment]
> 我看了，没同步。。。下次可以开解析器订阅surge的模块

好的，谢谢你
