### ISSUE TITLE
番茄 5.6.7 广告失效

### ISSUE THREAD

**Issue by deckvig** [zqzess/rule_for_quantumultX#49]
IOS: 17.0.1
番茄: 5.6.7
关闭其他重写和规则后，还是会有广告

**Comment by zqzess** [comment]
我正在看番茄小说呢……
检查一下mitm，重写是否开启，
点开番茄小说随便找本书多刷几章看看还有没有广告，还不行重装番茄小说吧。

**Comment by zqzess** [comment]
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/49cced20-2fd8-422a-9634-520f388b2312)
目前的规则应该只会像上图那样，偶尔章末出现一个小横幅，但是不会影响到你阅读

**Comment by zqzess** [comment]
目前来反馈的大多是圈x用户说失效了，大概率是你配置有问题，虽然我用surge，但是圈x也会用来测试

**Comment by deckvig** [comment]
比较奇怪，相同的配置我在 iPhone 和 iPad 上都在用，但是 iPad 上一点问题没有，iPhone 上一直出广告。
重写和 mimt 都开了的。别的 App 去广告目前没啥问题。我手动 Reject 个别 img 的地址后会好一点，但是视频广告还是一直会弹出来。

确实是 qx，我再试试。

**Comment by zqzess** [comment]
qx的很迷，当年我用qx那会，装了b站的去广告重新，是那个爬虫佬bm7的，怎么搞都不行，后来装了nobyda的b站解锁1080p高画质能用，但是b站切区域又不行，一怒之下斥巨资换了loon和surge，这才舒服了

**Comment by deckvig** [comment]
😂后面不行换个 loon 试试

**Comment by zqzess** [comment]
loon目前还没人反馈出问题，群里之前有个反馈说失效了，换成surge立马正常😅

**Comment by deckvig** [comment]
搞定了，尝试了好久。真的是没想到是因为一个广告拦截列表导致的，里面全是 host，直接都走的 Reject 模式,但是居然会导致番茄去广告失效。
关闭后就完全没问题了
