### ISSUE TITLE
抖音无法刷新，另MyJSrewrite中报错两条

### ISSUE THREAD

**Issue by HoGafi** [zqzess/rule_for_quantumultX#5]
感谢大大的整合付出

**Comment by zqzess** [comment]
> 感谢大大的整合付出

抖音最新版配置了防解密，检查是否加了其他人的重写，我的已经全部移除，或着mitm添加-*.amemv.com
MyJsRewrite订阅需要开启资源解析器

**Comment by HoGafi** [comment]
> > 感谢大大的整合付出
> 
> 抖音最新版配置了防解密，检查是否加了其他人的重写，我的已经全部移除，或着mitm添加-*.amemv.com
> MyJsRewrite订阅需要开启资源解析器

谢谢大大，已开资源解析器，主要是workingcopy和musicmatch两个脚本报404，网络已翻墙

**Comment by zqzess** [comment]
> > > 感谢大大的整合付出
> 
> > 
> 
> > 抖音最新版配置了防解密，检查是否加了其他人的重写，我的已经全部移除，或着mitm添加-*.amemv.com
> 
> > MyJsRewrite订阅需要开启资源解析器
> 
> 
> 
> 谢谢大大，已开资源解析器，主要是workingcopy和musicmatch两个脚本报404，网络已翻墙

估计失效了然后被原作者删除了，musicmatch晚上我换个源

**Comment by HoGafi** [comment]
> > > > 感谢大大的整合付出
> > 
> > 
> > > 
> > 
> > 
> > > 抖音最新版配置了防解密，检查是否加了其他人的重写，我的已经全部移除，或着mitm添加-*.amemv.com
> > 
> > 
> > > MyJsRewrite订阅需要开启资源解析器
> > 
> > 
> > 谢谢大大，已开资源解析器，主要是workingcopy和musicmatch两个脚本报404，网络已翻墙
> 
> 估计失效了然后被原作者删除了，musicmatch晚上我换个源

感谢，希望能够整合更多vip的😁
