### ISSUE TITLE
圈X的番茄规则误杀了抖音直播

### ISSUE THREAD

**Issue by koukisakurai** [zqzess/rule_for_quantumultX#50]
pull-hs-f5.flive.douyincdn.com:80 应该是这条被重定向了

**Comment by zqzess** [comment]
用 surge 的模块

**Comment by aywuyan** [comment]
> 用 surge 的模块

USER-AGENT ttplayer* 目前来看这条规则把抖音直播干掉了。
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54765246/a7a69202-f98d-4062-9977-cdcab97c0929)

**Comment by zqzess** [comment]
> > 用 surge 的模块
> 
> USER-AGENT ttplayer* 目前来看这条规则把抖音直播干掉了。 ![image](https://user-images.githubusercontent.com/54765246/275923763-a7a69202-f98d-4062-9977-cdcab97c0929.jpeg)


@honue 
这个还会干掉抖音直播啊

**Comment by zqzess** [comment]
> > 用 surge 的模块
> 
> USER-AGENT ttplayer* 目前来看这条规则把抖音直播干掉了。 ![image](https://user-images.githubusercontent.com/54765246/275923763-a7a69202-f98d-4062-9977-cdcab97c0929.jpeg)

这个已经注释了，更新就好了
