### ISSUE TITLE
番茄小说内部广告又出来了😭

### ISSUE THREAD

**Issue by xiaolizi111** [zqzess/rule_for_quantumultX#51]

**Comment by xiaolizi111** [comment]
就是番茄下边的广告出现，还有在阅读中偶尔会有一面等五秒的广告

**Comment by zqzess** [comment]
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/7997a180-1c98-48f3-ae47-b8a3a9cbf2b1)
你一定是用的圈x，检查一下自己的配置，规则没问题

**Comment by xiaolizi111** [comment]
好的十分感谢您的回答，我再去调试一下。

zqzess ***@***.***>于2023年11月5日 周日08:24写道：
