### ISSUE TITLE
阿里网盘签到

### ISSUE THREAD

**Issue by LazyIonEs** [zqzess/rule_for_quantumultX#52]
希望阿里网盘签到结束后增加Quantumult X通知，告知签到情况

**Comment by zqzess** [comment]
yi zhi![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/0f6f049a-a1a4-4948-9d81-a7a6a415ba84)
一直都有通知
没有通知那就检查你是不是关闭了，或者免打扰了

**Comment by LazyIonEs** [comment]
我这边使用Quantumult X确实没有收到通知，设置中只关闭了策略检测通知，也并没有开启免打扰，其他脚本的正常通知

**Comment by LazyIonEs** [comment]
![IMG_0745](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/6240c42e-c2ca-4633-b7e2-f1989c4a556d)
感觉我的好像有点不一样，结果也没有显示出来

**Comment by zqzess** [comment]
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/9cea634c-c28d-4000-89ce-8a8fc49575a7)
这是我的

**Comment by zqzess** [comment]
> ![IMG_0745](https://user-images.githubusercontent.com/86482436/285332643-6240c42e-c2ca-4633-b7e2-f1989c4a556d.png) 感觉我的好像有点不一样，结果也没有显示出来

你这看起来脚本没跑完就中断了

**Comment by LazyIonEs** [comment]
是这样嘛，我一直没有注意

**Comment by zqzess** [comment]
> 是这样嘛，我一直没有注意

![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/bd7bab5a-a058-4012-87f8-1eb073dec6f9)
你这可能是 message 有内容，脚本结束了，你可以console.log()打印看一下，提示了啥信息

**Comment by zqzess** [comment]
> > 是这样嘛，我一直没有注意
> 
> ![image](https://user-images.githubusercontent.com/54464797/285333520-bd7bab5a-a058-4012-87f8-1eb073dec6f9.png) 你这可能是 message 有内容，脚本结束了，你可以console.log()打印看一下，提示了啥信息
```javascript
            if(body.message!==null)
                {
                   console.log(body.message)
                   $.done()
                }
```

**Comment by LazyIonEs** [comment]
> > > 是这样嘛，我一直没有注意
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54464797/285333520-bd7bab5a-a058-4012-87f8-1eb073dec6f9.png) 你这可能是 message 有内容，脚本结束了，你可以console.log()打印看一下，提示了啥信息
> 
> ```js
>             if(body.message!==null)
>                 {
>                    console.log(body.message)
>                    $.done()
>                 }
> ```

我试一下

**Comment by zqzess** [comment]
或者你更新一下脚本，我刚加了日志打印，已经推送了

**Comment by LazyIonEs** [comment]
> 或者你更新一下脚本，我刚加了日志打印，已经推送了

![IMG_0749](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/9161dc3a-6ab7-4498-bf17-e50338595ec5)
打印信息 no login 
是不是我boxjs有问题呀

**Comment by zqzess** [comment]
> > 或者你更新一下脚本，我刚加了日志打印，已经推送了
> 
> ![IMG_0749](https://user-images.githubusercontent.com/86482436/285334417-9161dc3a-6ab7-4498-bf17-e50338595ec5.jpeg) 打印信息 not login 是不是我boxjs有问题呀

你可以把内容全部清空，重新拉 token 试试

**Comment by zqzess** [comment]
> > 或者你更新一下脚本，我刚加了日志打印，已经推送了
> 
> ![IMG_0749](https://user-images.githubusercontent.com/86482436/285334417-9161dc3a-6ab7-4498-bf17-e50338595ec5.jpeg) 打印信息 not login 是不是我boxjs有问题呀

你这确实有点问题，你这边都是以 object 展示的，但是我的圈 x是能看到具体内容的，json 字符串展示的

**Comment by LazyIonEs** [comment]
![IMG_0750](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/4a6e12bb-3b2e-49ad-9ed2-85c8e1c8a8ae)
![IMG_0751](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/7b9c5b27-74c7-4b36-be95-a1239445e25c)
![IMG_0752](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/224e2f64-dbb7-4d29-9e90-6a599066c213)
![IMG_0753](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/d3c6a1c8-c723-492f-8436-a64180eb3684)
重新拉token确实可以，但是第一次手动执行没有收到通知，应该是到领取奖励那一步就结束了，第二次执行就有了

**Comment by LazyIonEs** [comment]
> > > 或者你更新一下脚本，我刚加了日志打印，已经推送了
> > 
> > 
> > ![IMG_0749](https://user-images.githubusercontent.com/86482436/285334417-9161dc3a-6ab7-4498-bf17-e50338595ec5.jpeg) 打印信息 not login 是不是我boxjs有问题呀
> 
> 你这确实有点问题，你这边都是以 object 展示的，但是我的圈 x是能看到具体内容的，json 字符串展示的

现在看boxjs也正常了，前两个参数显示json数据

**Comment by LazyIonEs** [comment]
我知道为啥我收不到通知了，到这一步就结束了，没有显示领取了什么奖励
![IMG_0755](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/1d7a786d-654c-4d0d-b7fb-dc31ab309859)

**Comment by zqzess** [comment]
> > ![image](https://private-user-images.githubusercontent.com/54464797/285332777-9cea634c-c28d-4000-89ce-8a8fc49575a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc1MjMsIm5iZiI6MTcwMTA0NzIyMywicGF0aCI6Ii81NDQ2NDc5Ny8yODUzMzI3NzctOWNlYTYzNGMtYzI4ZC00MDAwLTg5Y2UtOGE4ZmM0OTU3NWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzMzNGY3ZjZmMDA5YzZmYmU1ZjM3ODU2NzUyYTY3NTlmMjNlOGI2MjM4MTFhYTAyMzU5NTRkNDI5ZGVkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndRUHp0afC7n3xfmgw8vZmS5xBiRnHw3AcE6YM191TQ) 这是我的
> 
> 这个是今天已经签到过的，我这边要是签到后再执行也会通知，但是每天第一次，一般都是设置一个定时任务嘛，不确定是不是就会出现我这样的问题

你这个有点特殊，我每天都有通知，有时候通知会不显示领取到什么签到奖励，一般是什么好运签那种会没有奖励显示，如果是延期，会员，容量是肯定会在通知里展示的

**Comment by LazyIonEs** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/54464797/285332777-9cea634c-c28d-4000-89ce-8a8fc49575a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc1MjMsIm5iZiI6MTcwMTA0NzIyMywicGF0aCI6Ii81NDQ2NDc5Ny8yODUzMzI3NzctOWNlYTYzNGMtYzI4ZC00MDAwLTg5Y2UtOGE4ZmM0OTU3NWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzMzNGY3ZjZmMDA5YzZmYmU1ZjM3ODU2NzUyYTY3NTlmMjNlOGI2MjM4MTFhYTAyMzU5NTRkNDI5ZGVkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndRUHp0afC7n3xfmgw8vZmS5xBiRnHw3AcE6YM191TQ) 这是我的
> > 
> > 
> > 这个是今天已经签到过的，我这边要是签到后再执行也会通知，但是每天第一次，一般都是设置一个定时任务嘛，不确定是不是就会出现我这样的问题
> 
> 你这个有点特殊，我每天都有通知，有时候通知会不显示领取到什么签到奖励，一般是什么好运签那种会没有奖励显示，如果是延期，会员，容量是肯定会在通知里展示的

我也不确定怎么回事，但是确实没有通知，我这几天一直在观察这个脚本，第一次确实没有，我再次手动执行的时候，就会有通知

**Comment by zqzess** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/54464797/285332777-9cea634c-c28d-4000-89ce-8a8fc49575a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc1MjMsIm5iZiI6MTcwMTA0NzIyMywicGF0aCI6Ii81NDQ2NDc5Ny8yODUzMzI3NzctOWNlYTYzNGMtYzI4ZC00MDAwLTg5Y2UtOGE4ZmM0OTU3NWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzMzNGY3ZjZmMDA5YzZmYmU1ZjM3ODU2NzUyYTY3NTlmMjNlOGI2MjM4MTFhYTAyMzU5NTRkNDI5ZGVkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndRUHp0afC7n3xfmgw8vZmS5xBiRnHw3AcE6YM191TQ) 这是我的
> > > 
> > > 
> > > 这个是今天已经签到过的，我这边要是签到后再执行也会通知，但是每天第一次，一般都是设置一个定时任务嘛，不确定是不是就会出现我这样的问题
> > 
> > 
> > 你这个有点特殊，我每天都有通知，有时候通知会不显示领取到什么签到奖励，一般是什么好运签那种会没有奖励显示，如果是延期，会员，容量是肯定会在通知里展示的
> 
> 我也不确定怎么回事，但是确实没有通知，我这几天一直在观察这个脚本，第一次确实没有，我再次手动执行的时候，就会有通知

你看看你是不是走了代码，或者账号问题，目前我就遇到你一个有这问题

**Comment by zqzess** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/54464797/285332777-9cea634c-c28d-4000-89ce-8a8fc49575a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDc1MjMsIm5iZiI6MTcwMTA0NzIyMywicGF0aCI6Ii81NDQ2NDc5Ny8yODUzMzI3NzctOWNlYTYzNGMtYzI4ZC00MDAwLTg5Y2UtOGE4ZmM0OTU3NWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzMzNGY3ZjZmMDA5YzZmYmU1ZjM3ODU2NzUyYTY3NTlmMjNlOGI2MjM4MTFhYTAyMzU5NTRkNDI5ZGVkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ndRUHp0afC7n3xfmgw8vZmS5xBiRnHw3AcE6YM191TQ) 这是我的
> > > > 
> > > > 
> > > > 这个是今天已经签到过的，我这边要是签到后再执行也会通知，但是每天第一次，一般都是设置一个定时任务嘛，不确定是不是就会出现我这样的问题
> > > 
> > > 
> > > 你这个有点特殊，我每天都有通知，有时候通知会不显示领取到什么签到奖励，一般是什么好运签那种会没有奖励显示，如果是延期，会员，容量是肯定会在通知里展示的
> > 
> > 
> > 我也不确定怎么回事，但是确实没有通知，我这几天一直在观察这个脚本，第一次确实没有，我再次手动执行的时候，就会有通知
> 
> 你看看你是不是走了代理，或者账号问题，目前我就遇到你一个有这问题

**Comment by zqzess** [comment]
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/91034c60-d18d-4911-93fc-6bff925929c1)
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/a5d9c2bc-0fd8-49d9-a6ce-346be02c5b79)
你看，这是我的两个执行日志

**Comment by LazyIonEs** [comment]
![IMG_0757](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/efd3d210-a846-421a-b701-55db0a2fd88a)
没有走代理，今天的，第一次没有相应，然后应该是重试了吧

**Comment by LazyIonEs** [comment]
> ![image](https://private-user-images.githubusercontent.com/54464797/285698612-91034c60-d18d-4911-93fc-6bff925929c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDkxOTIsIm5iZiI6MTcwMTA0ODg5MiwicGF0aCI6Ii81NDQ2NDc5Ny8yODU2OTg2MTItOTEwMzRjNjAtZDE4ZC00OTExLTkzZmMtNmJmZjkyNTkyOWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTExYzc2NTYxOWJiNGFhYWMyOTRiZTIwZDQyZjJhYjFiMjFhYzkxZWU0M2Q5YzU1MmZmNGNhNmFiZTA4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D3WwUTCV_C5HVTyPdphvurGOXMVAfL0fcFdyTRtF8sE) ![image](https://private-user-images.githubusercontent.com/54464797/285698621-a5d9c2bc-0fd8-49d9-a6ce-346be02c5b79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDkxOTIsIm5iZiI6MTcwMTA0ODg5MiwicGF0aCI6Ii81NDQ2NDc5Ny8yODU2OTg2MjEtYTVkOWMyYmMtMGZkOC00OWQ5LWE2Y2UtMzQ2YmUwMmM1Yjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAxMzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNGQ1NTE4MDI2MDQ4MjkwMmI4ZWZkYWEzNzM3NWRiMzU2M2EzOThlNGIwZWNiZTE0M2M0NGRlNDVlMzJhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-TsEyfRimi4kBVQFjT60LwxA40s-CZOwDpkTqLVtvA) 你看，这是我的两个执行日志

这个qx的在哪里可以看到，我翻一下看看

**Comment by LazyIonEs** [comment]
![IMG_0758](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/223f803b-7762-4390-bee9-edaf0968ab2e)

**Comment by LazyIonEs** [comment]
好吧，看来我的问题有点特殊，可能跟其他的配置冲突了吧，我自己研究研究吧

**Comment by LazyIonEs** [comment]
![img_v3_025m_8b4e5b8f-b5e3-40cf-9c40-928e0e087b0g](https://github.com/zqzess/rule_for_quantumultX/assets/86482436/dba93c08-c75a-4374-ae8d-13a54a326e42)
我自己的推测，不确定是不是因为这个

**Comment by zqzess** [comment]
1. 这边的网络请求是同步的，不是异步
2. 目前只有你反馈了这个问题，如果是异步+逻辑问题，那这个脚本应该是偶尔能签到成功。

**Comment by zqzess** [comment]
> ![img_v3_025m_8b4e5b8f-b5e3-40cf-9c40-928e0e087b0g](https://private-user-images.githubusercontent.com/86482436/286794050-dba93c08-c75a-4374-ae8d-13a54a326e42.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTAzODUsIm5iZiI6MTcwMTMxMDA4NSwicGF0aCI6Ii84NjQ4MjQzNi8yODY3OTQwNTAtZGJhOTNjMDgtYzc1YS00Mzc0LWFlOGQtMTNhNTRhMzI2ZTQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAyMDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzdmNDI2ODdjY2JlZGZiM2JhYjQ3ZjM5ZjRkOGJmMzZmNTBkMDc3OGQ3NjMyMDkwOTY0ZjJjMDI3MmY3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iqPISEL0T8TAaA8EAT03aQCg6wgd1GnasvXLzvK-cTs) 我自己的推测，不确定是不是因为这个


我更倾向于你账号有问题，自动领取没有拿到结果，你二次签到能通知获得了什么是因为自动领取和签到是 2 个接口

**Comment by LazyIonEs** [comment]
> > 
> 
> 我更倾向于你账号有问题，自动领取没有拿到结果，你二次签到能通知获得了什么是因为自动领取和签到是 2 个接口

get

**Comment by zqzess** [comment]
> > 1. 这边的网络请求是同步的，不是异步
> > 2. 目前只有你反馈了这个问题，如果是异步+逻辑问题，那这个脚本应该是偶尔能签到成功。
> 
> 好吧，可能跟我其他的配置有点冲突吧

<img width="839" alt="image" src="https://github.com/zqzess/rule_for_quantumultX/assets/54464797/c394fbef-43fa-46f2-af89-9f09ed73696d">

签到的接口返回值里面是能看到签到可以领取什么的，代码里面也能看到这一点，后面再次自动领取会把之前从签到接口获取的奖励给清空，然后使用自动领取接口获得的奖励。

**Comment by zqzess** [comment]
前 2天把签到接口又更新了下，现在领取到的奖励应该显示的会更多

**Comment by LazyIonEs** [comment]
> 前 2天把签到接口又更新了下，现在领取到的奖励应该显示的会更多

明天早上我在试一下

**Comment by zyu0090** [comment]
我也出现了同样的问题，定时任务不通知，手动执行时有通知的

**Comment by zqzess** [comment]
![image](https://github.com/zqzess/rule_for_quantumultX/assets/54464797/78d820d0-2711-4504-a07c-e563f73bdb12)
