### ISSUE TITLE
MyJsRewrite中kmh、xxys失效

### ISSUE THREAD

**Issue by HoGafi** [zqzess/rule_for_quantumultX#6]
如题，MyJsRewrite中kmh、xxys失效，已翻墙，已开资源解析器

**Comment by zqzess** [comment]
> 如题，MyJsRewrite中kmh、xxys失效，已翻墙，已开资源解析器

等我晚上下班看一下

**Comment by zqzess** [comment]
> 如题，MyJsRewrite中kmh、xxys失效，已翻墙，已开资源解析器

已移除失效并搬运更多fakeip
