### ISSUE TITLE
TikTok无法播放

### ISSUE THREAD

**Issue by w12928293** [zqzess/rule_for_quantumultX#7]
报错信息：
[QTXDataParser] Left side MitM error for api16-normal-c-alisg.tiktokv.com with optional ssl code -9808.
2021/09/26 09:31:34:840  <error>     
 [QTXDataParser] Left side MitM error for api16-normal-c-alisg.tiktokv.com with optional ssl code -9808.

试着更新你的重写，还是报这个错

**Comment by zqzess** [comment]
> 报错信息：
> 
> [QTXDataParser] Left side MitM error for api16-normal-c-alisg.tiktokv.com with optional ssl code -9808.
> 
> 2021/09/26 09:31:34:840  <error>     
> 
>  [QTXDataParser] Left side MitM error for api16-normal-c-alisg.tiktokv.com with optional ssl code -9808.
> 
> 
> 
> 试着更新你的重写，还是报这个错

这个应该是抖音的加密，但是我的mitm里面好像没有api16-normal-c-alisg.tiktokv.com这个啊，我等会看看

**Comment by zqzess** [comment]
> api16-normal-c-alisg.tiktokv.com

最简单的解决方法就是在mitm的hostname里面加上 -api16-normal-c-alisg.tiktokv.com

**Comment by w12928293** [comment]
不好意思，刚刚那个好像是我自己修改的配置文件报的错，我试着导入你的完整版配置文件，然后报错信息有差异：
2021/09/26 10:09:18:893  <error>      [QTXDataParser] Left side MitM error for api16-normal-c-alisg.tiktokv.com with optional ssl code -9808.

**Comment by w12928293** [comment]
添加之后，报错信息变了：
2021/09/26 10:13:47:153  <error>      [QTXDataParser] Left side MitM error for tnc16-platform-useast1a.tiktokv.com with optional ssl code -9808.
2021/09/26 10:13:47:170  <error>      [QTXDataParser] Left side MitM error for tnc31-platform-alisg.tiktokv.com with optional ssl code -9808.
2021/09/26 10:13:47:181  <error>      [QTXDataParser] Left side MitM error for dm22-alisg.tiktokv.com with optional ssl code -9808.
2021/09/26 10:13:47:987  <error>      [QTXDataParser] Left side MitM error for api16-core-c-alisg.tiktokv.com with optional ssl code -9808.
2021/09/26 10:13:48:136  <error>      [QTXDataParser] Left side MitM error for api16-core-c-alisg.tiktokv.com with optional ssl code -9808.
2021/09/26 10:13:51:563  <error>      [QTXDataParser] Left side MitM error for log.tiktokv.com with optional ssl code -9808.
2021/09/26 10:13:51:714  <error>      [QTXDataParser] Left side MitM error for log.tiktokv.com with optional ssl code -9808.

**Comment by w12928293** [comment]
这个问题很神奇，我是因为更换手机，但是配置文件全部都是传过来的，其他的也都没有问题，就tiktok这里报错

**Comment by zqzess** [comment]
> 这个问题很神奇，我是因为更换手机，但是配置文件全部都是传过来的，其他的也都没有问题，就tiktok这里报错

应该是最新版tiktol导致的
你可以试试 -tiktokv.com ，加这个，或者你找一下mitm里面有tiktok的是哪个，把它去掉。这可能不是我写的，我没写过tiktok的

**Comment by w12928293** [comment]
多谢解答，应该是我在你的配置文件基础上引用的别人的tiktok解锁，我先排查下。

**Comment by zqzess** [comment]
> 多谢解答，应该是我在你的配置文件基础上引用的别人的tiktok解锁，我先排查下。

我配置文件里面有搬运过Tartarus2014的tiktok解锁，重写里面单独引用的，不知道是不是这个

**Comment by w12928293** [comment]
我重新检查了下配置文件，发现可能是因为tiktok启动的时候就会检查，所以失败，清空缓存不行，重新安装美区版，并切换节点到非香港区域就可以正常播放了。
感谢帮助！
