### ISSUE TITLE
Google App 无法加载资讯，提示出了点问题请稍后重试。

### ISSUE THREAD

**Issue by gqbre** [zqzess/rule_for_quantumultX#8]
QuantumultX 使用 MyRewrite 重写规则导致，应该是 google 重定向规则导致的问题。
目前看这个规则似乎没有必要？浏览器访问一次  https://www.google.com/ncr 就能实现需求

**Comment by zqzess** [comment]
> QuantumultX 使用 MyRewrite 重写规则导致，应该是 google 重定向规则导致的问题。
> 
> 目前看这个规则似乎没有必要？浏览器访问一次  https://www.google.com/ncr 就能实现需求

谷歌app你是指的chrome嘛，主页下面那个资讯我可以正常使用使用，然后重定向有必要，你说的ncr在六七月查的最严的时候无法重定向。

**Comment by zqzess** [comment]
> QuantumultX 使用 MyRewrite 重写规则导致，应该是 google 重定向规则导致的问题。
> 
> 目前看这个规则似乎没有必要？浏览器访问一次  https://www.google.com/ncr 就能实现需求

你可以订阅单个重写，不用订阅Mywrite，这个是合集，圈x文件夹下有分开的单个功能订阅

**Comment by zqzess** [comment]
> QuantumultX 使用 MyRewrite 重写规则导致，应该是 google 重定向规则导致的问题。
> 
> 目前看这个规则似乎没有必要？浏览器访问一次  https://www.google.com/ncr 就能实现需求

我又去问了另一个人，他也正常，如果你说的谷歌app就是chrome的话，你换个节点试试，或者排查是否有其他订阅冲突了

**Comment by gqbre** [comment]
外区搜索 google 第一个应用就是
https://apps.apple.com/us/app/google/id284815942

**Comment by gqbre** [comment]
这个重定向还有个问题，Safari 历史记录，清除所有时间。打开 https://www.google.com.hk/ 会重定向到一个 404页面，访问一次 /ncr 后再次重新访问则正常

**Comment by zqzess** [comment]
> 这个重定向还有个问题，Safari 历史记录，清除，所有时间。直接访问 https://www.google.com.hk/ 会重定向到一个 404页面，访问一次 /ncr 后再次重新访问则正常

我试了，google应用咨询正常,``https://www.goole.com.hk/``也会正常定向到``https://www.google.com/webhp``,不会报404

只有圈X的配置是把谷歌定向到``https://www.google.com/search``的，Loon和surge都是定向到``https://www.google.com/ncr``原因就是六七月的时候圈X会报错404

**Comment by zqzess** [comment]
> 这个重定向还有个问题，Safari 历史记录，清除，所有时间。直接访问 https://www.google.com.hk/ 会重定向到一个 404页面，访问一次 /ncr 后再次重新访问则正常

你可以tg私聊我@zqzess
