### ISSUE TITLE
youtube广告去不掉

### ISSUE THREAD

**Issue by Yiweiwangau** [zqzess/rule_for_quantumultX#9]
您好，我在quantumultX
使用了您的https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/zqzess.conf规则。
例如bilibili的开屏广告已经都能去掉了，youtube我能看到有rewite的活动但是广告还是存在，请问我是还应该加入其他的一些什么规则吗？
谢谢

**Comment by zqzess** [comment]
> 您好，我在quantumultX
> 
> 使用了您的https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/zqzess.conf规则。
> 
> 例如bilibili的开屏广告已经都能去掉了，youtube我能看到有rewite的活动但是广告还是存在，请问我是还应该加入其他的一些什么规则吗？
> 
> 谢谢

如果你连视频播放中的广告也无法跳过，看一下是否开启mitm

**Comment by Yiweiwangau** [comment]
![image](https://user-images.githubusercontent.com/81563224/138198768-589fc2cc-37b6-4853-b087-c5cdec53097b.png)![image](https://user-images.githubusercontent.com/81563224/138198777-9fa6439e-266a-491b-8b71-b75c44f0af73.png)![image](https://user-images.githubusercontent.com/81563224/138198782-8f81bdc7-4348-4a37-a174-c64f8abb65b3.png)
您好，是几秒钟跳过的广告去不了，mitm是开启的，youtube是能看到rewrite的，是我设置有问题吗？

**Comment by zqzess** [comment]
> ![image](https://user-images.githubusercontent.com/81563224/138198768-589fc2cc-37b6-4853-b087-c5cdec53097b.png)![image](https://user-images.githubusercontent.com/81563224/138198777-9fa6439e-266a-491b-8b71-b75c44f0af73.png)![image](https://user-images.githubusercontent.com/81563224/138198782-8f81bdc7-4348-4a37-a174-c64f8abb65b3.png)
> 您好，是几秒钟跳过的广告去不了，mitm是开启的，youtube是能看到rewrite的，是我设置有问题吗？

你把你看的视频链接发给我，我看看是咋回事，我这边使用正常

**Comment by Yiweiwangau** [comment]
https://youtu.be/HnLE9kCufRU
您试试这个

**Comment by zqzess** [comment]
> https://youtu.be/HnLE9kCufRU
> 您试试这个

我这边正常跳过

你看看你有没有下面类似我这样的重写，302跳转指向
![image](https://user-images.githubusercontent.com/54464797/138202492-7a294eb1-3971-45fc-bfa3-d2ea86ec3d35.png)

**Comment by Yiweiwangau** [comment]
不好意思没有，我这里只有200，所以我在想我是不是什么地方设置错了

![image](https://user-images.githubusercontent.com/81563224/138203730-6d699af7-e8af-4959-88f2-c83fae6c837d.png)

**Comment by Yiweiwangau** [comment]
不是会员，请问一下正常操作是应该直接把https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/zqzess.conf导入quantumultX,不需要再导入些别的了吧

**Comment by Yiweiwangau** [comment]
您好，想再问一下，流量下无网该怎么办，
显示dns fail，我改了出站规则为强制蜂窝网也不行。谢谢
![image](https://user-images.githubusercontent.com/81563224/138373100-e4a64e0b-e58f-441b-a825-5f3b9e9d1352.png)

**Comment by zqzess** [comment]
> 您好，想再问一下，流量下无网该怎么办，
> 显示dns fail，我改了出站规则为强制蜂窝网也不行。谢谢
> ![image](https://user-images.githubusercontent.com/81563224/138373100-e4a64e0b-e58f-441b-a825-5f3b9e9d1352.png)

我只知道一种情况会出现这个问题，

圈x配置文件里面的dns模块，把下面的dns服务器全删了，再加上no-system会导致dns fail。其他就不清楚了
